# Generated by Django 4.2.7 on 2023-12-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('login', models.CharField(blank=True, max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=128)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('balance', models.IntegerField(blank=True, default=0)),
                ('card_number', models.CharField(blank=True, max_length=19)),
                ('card_CVC', models.CharField(blank=True, max_length=3)),
                ('card_date', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('discount', models.IntegerField(default=0)),
                ('in_stock', models.IntegerField(default=10)),
                ('rating', models.FloatField(blank=True, default=0.0)),
                ('count_rating', models.IntegerField(blank=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='shop.company')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='shop.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='shop.users')),
            ],
        ),
    ]
